# This workflow will generate a PR for changes in dev into master for a skill

name: Request PR Review
on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  assign_review:
    runs-on: ubuntu-latest
    steps:
      - name: assign-review-action
        uses: delivery-much/actions-assigner@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team-reviewers: NeonDevs